#!/usr/bin/env bash

# For more settings refer to ~/.macos — https://mths.be/macos

# Ask for password
sudo -v

enable_touch_id_in_terminal() {
  if ! grep -q "pam_tid.so" /etc/pam.d/sudo
  then
    sudo sed -i~ '2i\
      auth sufficient pam_tid.so
      ' /etc/pam.d/sudo
    sudo sed -i~ '2i\
      auth optional pam_reattach.so
      ' /etc/pam.d/sudo
  fi
}

# Enabling TouchID for sudo
enable_touch_id_in_terminal

# Enable italics font in iTerm2 and tmux
tic -x ./setup/tmux-256color.terminfo
tic ./setup/xterm-256color.terminfo
